[
  "<ignored>",
  "<ignored>",
  "<ignored>",
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/javascript/rules",
    "plugins": [
      "antfu",
      "unused-imports",
    ],
    "rules": [
      "accessor-pairs",
      "antfu/no-top-level-await",
      "array-callback-return",
      "block-scoped-var",
      "constructor-super",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-async-promise-executor",
      "no-caller",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-console",
      "no-const-assign",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-eval",
      "no-ex-assign",
      "no-extend-native",
      "no-extra-bind",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-implied-eval",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-iterator",
      "no-labels",
      "no-lone-blocks",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-native-nonconstructor",
      "no-new-wrappers",
      "no-obj-calls",
      "no-octal",
      "no-octal-escape",
      "no-proto",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "no-self-assign",
      "no-self-compare",
      "no-sequences",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-template-curly-in-string",
      "no-this-before-super",
      "no-throw-literal",
      "no-undef",
      "no-undef-init",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-unneeded-ternary",
      "no-unreachable",
      "no-unreachable-loop",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unused-expressions",
      "no-unused-vars",
      "no-use-before-define",
      "no-useless-backreference",
      "no-useless-call",
      "no-useless-catch",
      "no-useless-computed-key",
      "no-useless-constructor",
      "no-useless-rename",
      "no-useless-return",
      "no-var",
      "no-with",
      "object-shorthand",
      "one-var",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-exponentiation-operator",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "symbol-description",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "use-isnan",
      "valid-typeof",
      "vars-on-top",
      "yoda",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/imports/rules",
    "plugins": [
      "antfu",
      "import",
    ],
    "rules": [
      "antfu/import-dedupe",
      "antfu/no-import-dist",
      "antfu/no-import-node-modules-by-path",
      "import/consistent-type-specifier-style",
      "import/first",
      "import/newline-after-import",
      "import/no-duplicates",
      "import/no-mutable-exports",
      "import/no-named-default",
    ],
  },
  {
    "name": "renton/comments/setup",
    "plugins": [
      "eslint-comments",
    ],
  },
  {
    "name": "renton/comments/rules",
    "rules": [
      "eslint-comments/disable-enable-pair",
      "eslint-comments/no-aggregating-enable",
      "eslint-comments/no-duplicate-disable",
      "eslint-comments/no-unlimited-disable",
      "eslint-comments/no-unused-enable",
    ],
  },
  {
    "name": "renton/command/rules",
    "plugins": [
      "command",
    ],
    "rules": [
      "command/command",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/perfectionist/rules",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-array-includes",
      "perfectionist/sort-classes",
      "perfectionist/sort-decorators",
      "perfectionist/sort-enums",
      "perfectionist/sort-export-attributes",
      "perfectionist/sort-exports",
      "perfectionist/sort-heritage-clauses",
      "perfectionist/sort-import-attributes",
      "perfectionist/sort-imports",
      "perfectionist/sort-interfaces",
      "perfectionist/sort-intersection-types",
      "perfectionist/sort-maps",
      "perfectionist/sort-modules",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
      "perfectionist/sort-object-types",
      "perfectionist/sort-objects",
      "perfectionist/sort-sets",
      "perfectionist/sort-switch-case",
      "perfectionist/sort-union-types",
      "perfectionist/sort-variable-declarations",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/node/rules",
    "plugins": [
      "node",
    ],
    "rules": [
      "node/handle-callback-err",
      "node/no-deprecated-api",
      "node/no-exports-assign",
      "node/no-new-require",
      "node/no-path-concat",
      "node/process-exit-as-throw",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/jsdoc/rules",
    "plugins": [
      "jsdoc",
    ],
    "rules": [
      "jsdoc/check-access",
      "jsdoc/check-param-names",
      "jsdoc/check-property-names",
      "jsdoc/check-tag-names",
      "jsdoc/check-types",
      "jsdoc/empty-tags",
      "jsdoc/implements-on-classes",
      "jsdoc/no-defaults",
      "jsdoc/no-multi-asterisks",
      "jsdoc/require-asterisk-prefix",
      "jsdoc/require-description",
      "- jsdoc/require-jsdoc",
      "- jsdoc/require-param",
      "- jsdoc/require-param-description",
      "- jsdoc/require-param-type",
      "- jsdoc/require-property",
      "- jsdoc/require-property-description",
      "- jsdoc/require-property-type",
      "- jsdoc/require-returns",
      "jsdoc/require-returns-check",
      "- jsdoc/require-returns-description",
      "- jsdoc/require-returns-type",
      "jsdoc/require-throws",
      "- jsdoc/require-yields",
      "jsdoc/require-yields-check",
      "jsdoc/tag-lines",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
    },
    "name": "renton/jsx/setup",
    "plugins": [],
    "rules": [],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "sourceType": "module",
      },
    },
    "name": "renton/typescript/setup",
    "plugins": [
      "ts",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "renton/typescript/rules",
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "- no-loss-of-precision",
      "- no-unused-vars",
      "ts/ban-ts-comment",
      "ts/consistent-type-definitions",
      "ts/consistent-type-imports",
      "- ts/no-dynamic-delete",
      "ts/no-empty-object-type",
      "- ts/no-explicit-any",
      "- ts/no-non-null-assertion",
      "- ts/no-require-imports",
      "ts/no-unused-vars",
      "ts/prefer-literal-enum-member",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/regexp/rules",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "- no-empty-character-class",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "regexp/strict",
      "regexp/use-ignore-case",
    ],
  },
  {
    "name": "renton/test/setup",
    "plugins": [
      "test",
    ],
  },
  {
    "files": [
      "**/__tests__/**/*.?([cm])[jt]s?(x)",
      "**/*.spec.?([cm])[jt]s?(x)",
      "**/*.test.?([cm])[jt]s?(x)",
      "**/*.bench.?([cm])[jt]s?(x)",
      "**/*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "renton/test/rules",
    "rules": [
      "test/consistent-test-it",
      "test/no-identical-title",
      "test/no-import-node-test",
      "test/no-only-tests",
      "test/prefer-hooks-in-order",
      "test/prefer-lowercase-title",
      "- antfu/no-top-level-await",
      "- no-unused-expressions",
      "- ts/explicit-function-return-type",
    ],
  },
  {
    "files": [
      "**/*.json",
      "**/*.json5",
      "**/*.jsonc",
    ],
    "language": "jsonc/x",
    "name": "renton/jsonc/rules",
    "plugins": [
      "jsonc",
    ],
    "rules": [
      "jsonc/no-bigint-literals",
      "jsonc/no-binary-expression",
      "jsonc/no-binary-numeric-literals",
      "jsonc/no-dupe-keys",
      "jsonc/no-escape-sequence-in-identifier",
      "jsonc/no-number-props",
      "jsonc/no-numeric-separators",
      "jsonc/no-parenthesized",
      "jsonc/no-plus-sign",
      "jsonc/no-regexp-literals",
      "jsonc/no-sparse-arrays",
      "jsonc/no-template-literals",
      "jsonc/no-undefined-value",
      "jsonc/no-unicode-codepoint-escapes",
      "jsonc/no-useless-escape",
      "jsonc/space-unary-ops",
      "jsonc/valid-json-number",
      "jsonc/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "files": [
      "**/package.json",
    ],
    "name": "renton/sort/package-json",
    "rules": [
      "jsonc/sort-array-values",
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "**/[jt]sconfig.json",
      "**/[jt]sconfig.*.json",
    ],
    "name": "renton/sort/tsconfig-json",
    "rules": [
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "package.json",
      "**/package.json",
    ],
    "languageOptions": {
      "parser": "jsonc-eslint-parser",
    },
    "name": "renton/pnpm/package-json",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/json-enforce-catalog",
      "pnpm/json-prefer-workspace-settings",
      "pnpm/json-valid-catalog",
    ],
  },
  {
    "files": [
      "pnpm-workspace.yaml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "renton/pnpm/pnpm-workspace-yaml",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/yaml-enforce-settings",
      "pnpm/yaml-no-duplicate-catalog-item",
      "pnpm/yaml-no-unused-catalog-item",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "language": "yaml/yaml",
    "name": "renton/yaml/rules",
    "plugins": [
      "yaml",
    ],
    "rules": [
      "yaml/block-mapping",
      "yaml/block-sequence",
      "yaml/no-empty-document",
      "yaml/no-empty-key",
      "yaml/no-empty-mapping-value",
      "yaml/no-empty-sequence-entry",
      "yaml/no-irregular-whitespace",
      "yaml/no-tab-indent",
      "yaml/plain-scalar",
      "yaml/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "name": "renton/markdown/setup",
    "plugins": [
      "markdown",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "renton/markdown/parser",
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/unicorn/rules",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "- logical-assignment-operators",
      "- no-negated-condition",
      "- no-nested-ternary",
      "- no-process-exit",
      "unicorn/better-dom-traversing",
      "unicorn/catch-error-name",
      "unicorn/class-reference-in-static-methods",
      "- unicorn/comment-content",
      "- unicorn/consistent-arrow-return-style",
      "unicorn/consistent-assert",
      "unicorn/consistent-boolean-name",
      "unicorn/consistent-class-member-order",
      "unicorn/consistent-compound-words",
      "unicorn/consistent-conditional-object-spread",
      "unicorn/consistent-date-clone",
      "- unicorn/consistent-destructuring",
      "unicorn/consistent-empty-array-spread",
      "unicorn/consistent-existence-index-check",
      "unicorn/consistent-export-decorator-position",
      "unicorn/consistent-function-scoping",
      "- unicorn/consistent-function-style",
      "unicorn/consistent-json-file-read",
      "unicorn/consistent-optional-chaining",
      "unicorn/consistent-template-literal-escape",
      "unicorn/consistent-tuple-labels",
      "- unicorn/custom-error-definition",
      "unicorn/default-export-style",
      "unicorn/dom-node-dataset",
      "unicorn/empty-brace-spaces",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/expiring-todo-comments",
      "unicorn/explicit-length-check",
      "unicorn/explicit-timer-delay",
      "unicorn/filename-case",
      "- unicorn/id-match",
      "unicorn/import-style",
      "unicorn/isolated-functions",
      "- unicorn/iteration-fallback-style",
      "unicorn/logical-assignment-operators",
      "unicorn/max-nested-calls",
      "unicorn/name-replacements",
      "unicorn/new-for-builtins",
      "unicorn/no-abusive-eslint-disable",
      "unicorn/no-accessor-recursion",
      "unicorn/no-accidental-bitwise-operator",
      "unicorn/no-anonymous-default-export",
      "unicorn/no-array-callback-reference",
      "unicorn/no-array-concat-in-loop",
      "unicorn/no-array-fill-with-reference-type",
      "unicorn/no-array-from-fill",
      "- unicorn/no-array-front-mutation",
      "unicorn/no-array-method-this-argument",
      "- unicorn/no-array-reduce",
      "unicorn/no-array-reverse",
      "unicorn/no-array-sort",
      "unicorn/no-array-sort-for-min-max",
      "unicorn/no-array-splice",
      "- unicorn/no-asterisk-prefix-in-documentation-comments",
      "unicorn/no-async-promise-finally",
      "- unicorn/no-await-expression-member",
      "unicorn/no-await-in-promise-methods",
      "- unicorn/no-barrel-files",
      "unicorn/no-blob-to-file",
      "unicorn/no-boolean-sort-comparator",
      "unicorn/no-break-in-nested-loop",
      "unicorn/no-canvas-to-image",
      "unicorn/no-chained-comparison",
      "unicorn/no-collection-bracket-access",
      "unicorn/no-computed-property-existence-check",
      "unicorn/no-confusing-array-splice",
      "unicorn/no-confusing-array-with",
      "unicorn/no-console-spaces",
      "unicorn/no-constant-zero-expression",
      "unicorn/no-declarations-before-early-exit",
      "unicorn/no-document-cookie",
      "unicorn/no-double-comparison",
      "unicorn/no-duplicate-if-branches",
      "unicorn/no-duplicate-logical-operands",
      "unicorn/no-duplicate-loops",
      "unicorn/no-duplicate-set-values",
      "unicorn/no-empty-file",
      "unicorn/no-error-property-assignment",
      "unicorn/no-exports-in-scripts",
      "unicorn/no-for-each",
      "unicorn/no-for-loop",
      "unicorn/no-global-object-property-assignment",
      "unicorn/no-immediate-mutation",
      "unicorn/no-impossible-length-comparison",
      "unicorn/no-incorrect-query-selector",
      "unicorn/no-incorrect-template-string-interpolation",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-argument-count",
      "unicorn/no-invalid-character-comparison",
      "unicorn/no-invalid-fetch-options",
      "- unicorn/no-invalid-file-input-accept",
      "unicorn/no-invalid-remove-event-listener",
      "unicorn/no-invalid-well-known-symbol-methods",
      "- unicorn/no-keyword-prefix",
      "unicorn/no-late-current-target-access",
      "unicorn/no-late-event-control",
      "unicorn/no-lonely-if",
      "unicorn/no-loop-iterable-mutation",
      "unicorn/no-magic-array-flat-depth",
      "- unicorn/no-manually-wrapped-comments",
      "unicorn/no-mismatched-map-key",
      "unicorn/no-misrefactored-assignment",
      "- unicorn/no-missing-local-resource",
      "unicorn/no-multiple-promise-resolver-calls",
      "unicorn/no-named-default",
      "unicorn/no-negated-array-predicate",
      "unicorn/no-negated-comparison",
      "unicorn/no-negated-condition",
      "unicorn/no-negation-in-equality-check",
      "unicorn/no-nested-ternary",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "unicorn/no-non-function-verb-prefix",
      "unicorn/no-nonstandard-builtin-properties",
      "- unicorn/no-null",
      "unicorn/no-object-as-default-parameter",
      "unicorn/no-object-methods-with-collections",
      "unicorn/no-optional-chaining-on-undeclared-variable",
      "- unicorn/no-process-exit",
      "unicorn/no-redundant-comparison",
      "unicorn/no-return-array-push",
      "unicorn/no-selector-as-dom-name",
      "unicorn/no-shorthand-property-overrides",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-static-only-class",
      "unicorn/no-subtraction-comparison",
      "unicorn/no-thenable",
      "unicorn/no-this-assignment",
      "unicorn/no-this-outside-of-class",
      "unicorn/no-top-level-assignment-in-function",
      "unicorn/no-top-level-side-effects",
      "unicorn/no-transition-all",
      "unicorn/no-typeof-undefined",
      "unicorn/no-uncalled-method",
      "unicorn/no-undeclared-class-members",
      "unicorn/no-unnecessary-array-flat-depth",
      "unicorn/no-unnecessary-array-flat-map",
      "unicorn/no-unnecessary-array-splice-count",
      "unicorn/no-unnecessary-await",
      "unicorn/no-unnecessary-boolean-comparison",
      "unicorn/no-unnecessary-fetch-options",
      "unicorn/no-unnecessary-global-this",
      "unicorn/no-unnecessary-nested-ternary",
      "unicorn/no-unnecessary-polyfills",
      "unicorn/no-unnecessary-slice-end",
      "unicorn/no-unnecessary-splice",
      "unicorn/no-unnecessary-string-trim",
      "unicorn/no-unreadable-array-destructuring",
      "unicorn/no-unreadable-for-of-expression",
      "unicorn/no-unreadable-iife",
      "- unicorn/no-unreadable-new-expression",
      "unicorn/no-unreadable-object-destructuring",
      "unicorn/no-unsafe-buffer-conversion",
      "- unicorn/no-unsafe-dom-html",
      "unicorn/no-unsafe-promise-all-settled-values",
      "unicorn/no-unsafe-property-key",
      "unicorn/no-unsafe-sqlite-interpolation",
      "unicorn/no-unsafe-string-replacement",
      "unicorn/no-unused-array-method-return",
      "- unicorn/no-unused-properties",
      "unicorn/no-useless-boolean-cast",
      "unicorn/no-useless-coercion",
      "unicorn/no-useless-collection-argument",
      "unicorn/no-useless-compound-assignment",
      "unicorn/no-useless-concat",
      "unicorn/no-useless-continue",
      "unicorn/no-useless-delete-check",
      "unicorn/no-useless-else",
      "unicorn/no-useless-error-capture-stack-trace",
      "unicorn/no-useless-fallback-in-spread",
      "unicorn/no-useless-iterator-to-array",
      "unicorn/no-useless-length-check",
      "unicorn/no-useless-logical-operand",
      "unicorn/no-useless-override",
      "unicorn/no-useless-promise-resolve-reject",
      "unicorn/no-useless-re-export",
      "unicorn/no-useless-recursion",
      "unicorn/no-useless-spread",
      "unicorn/no-useless-switch-case",
      "unicorn/no-useless-template-literals",
      "unicorn/no-useless-undefined",
      "unicorn/no-xor-as-exponentiation",
      "unicorn/no-zero-fractions",
      "unicorn/number-literal-case",
      "- unicorn/numeric-separators-style",
      "unicorn/operator-assignment",
      "unicorn/prefer-abort-signal-any",
      "unicorn/prefer-abort-signal-timeout",
      "unicorn/prefer-add-event-listener",
      "unicorn/prefer-add-event-listener-options",
      "unicorn/prefer-aggregate-error",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat",
      "unicorn/prefer-array-flat-map",
      "unicorn/prefer-array-from-async",
      "unicorn/prefer-array-from-map",
      "unicorn/prefer-array-from-range",
      "unicorn/prefer-array-index-of",
      "unicorn/prefer-array-iterable-methods",
      "unicorn/prefer-array-last-methods",
      "unicorn/prefer-array-slice",
      "unicorn/prefer-array-some",
      "- unicorn/prefer-at",
      "unicorn/prefer-await",
      "unicorn/prefer-bigint-literals",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-block-statement-over-iife",
      "unicorn/prefer-boolean-return",
      "unicorn/prefer-class-fields",
      "unicorn/prefer-classlist-toggle",
      "unicorn/prefer-code-point",
      "unicorn/prefer-continue",
      "unicorn/prefer-date-now",
      "unicorn/prefer-default-parameters",
      "unicorn/prefer-direct-iteration",
      "- unicorn/prefer-dispose",
      "unicorn/prefer-dom-node-append",
      "unicorn/prefer-dom-node-html-methods",
      "unicorn/prefer-dom-node-remove",
      "unicorn/prefer-dom-node-replace-children",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-early-return",
      "unicorn/prefer-else-if",
      "- unicorn/prefer-error-is-error",
      "unicorn/prefer-event-target",
      "- unicorn/prefer-explicit-viewport-units",
      "unicorn/prefer-export-from",
      "unicorn/prefer-flat-math-min-max",
      "unicorn/prefer-get-or-insert-computed",
      "unicorn/prefer-global-number-constants",
      "unicorn/prefer-global-this",
      "unicorn/prefer-group-by",
      "unicorn/prefer-has-check",
      "unicorn/prefer-hoisting-branch-code",
      "unicorn/prefer-https",
      "unicorn/prefer-identifier-import-export-specifiers",
      "- unicorn/prefer-import-meta-properties",
      "unicorn/prefer-includes",
      "unicorn/prefer-includes-over-repeated-comparisons",
      "unicorn/prefer-iterable-in-constructor",
      "- unicorn/prefer-iterator-concat",
      "unicorn/prefer-iterator-helpers",
      "unicorn/prefer-iterator-to-array",
      "unicorn/prefer-iterator-to-array-at-end",
      "unicorn/prefer-keyboard-event-key",
      "unicorn/prefer-location-assign",
      "unicorn/prefer-logical-operator-over-ternary",
      "unicorn/prefer-map-from-entries",
      "unicorn/prefer-math-abs",
      "unicorn/prefer-math-constants",
      "unicorn/prefer-math-min-max",
      "unicorn/prefer-math-trunc",
      "unicorn/prefer-minimal-ternary",
      "unicorn/prefer-modern-dom-apis",
      "unicorn/prefer-modern-math-apis",
      "- unicorn/prefer-module",
      "unicorn/prefer-native-coercion-functions",
      "unicorn/prefer-negative-index",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-coercion",
      "unicorn/prefer-number-is-safe-integer",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-object-define-properties",
      "unicorn/prefer-object-destructuring-defaults",
      "unicorn/prefer-object-from-entries",
      "unicorn/prefer-object-iterable-methods",
      "unicorn/prefer-observer-apis",
      "unicorn/prefer-optional-catch-binding",
      "unicorn/prefer-path2d",
      "unicorn/prefer-private-class-fields",
      "unicorn/prefer-promise-try",
      "unicorn/prefer-promise-with-resolvers",
      "unicorn/prefer-prototype-methods",
      "unicorn/prefer-query-selector",
      "unicorn/prefer-queue-microtask",
      "unicorn/prefer-reflect-apply",
      "- unicorn/prefer-regexp-escape",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-response-static-json",
      "unicorn/prefer-scoped-selector",
      "unicorn/prefer-set-has",
      "unicorn/prefer-set-methods",
      "unicorn/prefer-set-size",
      "- unicorn/prefer-short-arrow-method",
      "unicorn/prefer-simple-condition-first",
      "unicorn/prefer-simple-sort-comparator",
      "unicorn/prefer-simplified-conditions",
      "unicorn/prefer-single-array-predicate",
      "unicorn/prefer-single-call",
      "unicorn/prefer-single-object-destructuring",
      "unicorn/prefer-single-replace",
      "unicorn/prefer-smaller-scope",
      "unicorn/prefer-split-limit",
      "unicorn/prefer-spread",
      "unicorn/prefer-string-match-all",
      "unicorn/prefer-string-pad-start-end",
      "unicorn/prefer-string-raw",
      "unicorn/prefer-string-repeat",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-string-trim-start-end",
      "unicorn/prefer-structured-clone",
      "unicorn/prefer-switch",
      "- unicorn/prefer-temporal",
      "unicorn/prefer-ternary",
      "unicorn/prefer-then-catch",
      "unicorn/prefer-toggle-attribute",
      "- unicorn/prefer-top-level-await",
      "unicorn/prefer-type-error",
      "unicorn/prefer-type-literal-last",
      "- unicorn/prefer-uint8array-base64",
      "unicorn/prefer-unary-minus",
      "unicorn/prefer-unicode-code-point-escapes",
      "unicorn/prefer-url-can-parse",
      "unicorn/prefer-url-href",
      "unicorn/prefer-url-search-parameters",
      "unicorn/prefer-while-loop-condition",
      "unicorn/relative-url-style",
      "unicorn/require-array-join-separator",
      "unicorn/require-array-sort-compare",
      "unicorn/require-css-escape",
      "- unicorn/require-frontmatter-fields",
      "unicorn/require-module-attributes",
      "unicorn/require-module-specifiers",
      "unicorn/require-number-to-fixed-digits-argument",
      "unicorn/require-passive-events",
      "- unicorn/require-post-message-target-origin",
      "unicorn/require-proxy-trap-boolean-return",
      "unicorn/single-line-block-comment-style",
      "- unicorn/string-content",
      "unicorn/switch-case-braces",
      "unicorn/switch-case-break-position",
      "unicorn/template-indent",
      "unicorn/text-encoding-identifier-case",
      "unicorn/throw-new-error",
      "- unicorn/try-complexity",
      "- unicorn/no-array-for-each",
      "- unicorn/prevent-abbreviations",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/disables/scripts",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- ts/explicit-function-return-type",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "renton/disables/cli",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "renton/disables/bin",
    "rules": [
      "- antfu/no-import-dist",
      "- antfu/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "renton/disables/dts",
    "rules": [
      "- eslint-comments/no-unlimited-disable",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "renton/disables/cjs",
    "rules": [
      "- ts/no-require-imports",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "renton/disables/config-files",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- ts/explicit-function-return-type",
    ],
  },
]